# Generated by Django 5.0.4 on 2024-04-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Fun',
        ),
    ]
